/**
 * Fluid Functionalism 的语义图标槽位(mickadesign/fluid-functionalism@5ca7142):
 * registry/default/lib/icon-context.tsx 定义槽位,lib/docs/icon-map.tsx 给出各库的选图。
 * 槽位名描述角色而非字形——`more-horizontal` 在 Lucide 里叫 ellipsis。
 *
 * 值是该库内的图标名;库里没有对应字形时写完整 `set/name` 借用别的库,与 FF 的回退一致 (hugeicons/untitled-ui 的
 * play/pause 借 Lucide)。Phosphor 没有右侧栏字形,FF 用镜像 的 sidebar-simple,sigil 不做变换,借
 * Lucide 的 panel-right。
 */
export const FF_SLOTS = [
	'chevron-right',
	'chevron-down',
	'x',
	'copy',
	'menu',
	'dot',
	'monitor',
	'sun',
	'moon',
	'rectangle-horizontal',
	'circle',
	'square-library',
	'clock',
	'star',
	'settings',
	'plus',
	'arrow-left',
	'arrow-right',
	'arrow-up',
	'arrow-down',
	'search',
	'loader',
	'users',
	'lock',
	'mail',
	'bell',
	'shield',
	'palette',
	'lightbulb',
	'rocket',
	'heart',
	'paintbrush',
	'brain',
	'globe',
	'user',
	'image',
	'link',
	'check',
	'rotate-ccw',
	'play',
	'pause',
	'pipette',
	'home',
	'message-circle',
	'inbox',
	'pencil',
	'scaling',
	'skip-forward',
	'corner-down-right',
	'corner-down-left',
	'panel-left',
	'panel-right',
	'chevrons-up-down',
	'more-horizontal',
	'more-vertical',
	'calendar',
	'folder',
	'sliders-horizontal',
	'info',
] as const

export type FfSlot = (typeof FF_SLOTS)[number]

/** 与槽位同名的不必写;只列改了名的 */
const lucide: Partial<Record<FfSlot, string>> = {
	home: 'house',
	'more-horizontal': 'ellipsis',
	'more-vertical': 'ellipsis-vertical',
}

const tabler: Record<FfSlot, string> = {
	'chevron-right': 'chevron-right',
	'chevron-down': 'chevron-down',
	pipette: 'color-picker',
	x: 'x',
	copy: 'copy',
	menu: 'menu-2',
	dot: 'point',
	monitor: 'device-desktop',
	sun: 'sun',
	moon: 'moon',
	'rectangle-horizontal': 'square',
	circle: 'circle',
	'square-library': 'library',
	clock: 'clock',
	star: 'star',
	settings: 'settings',
	plus: 'plus',
	'arrow-left': 'arrow-left',
	'arrow-right': 'arrow-right',
	'arrow-up': 'arrow-up',
	'arrow-down': 'arrow-down',
	search: 'search',
	loader: 'loader-2',
	users: 'users',
	lock: 'lock',
	mail: 'mail',
	bell: 'bell',
	shield: 'shield',
	palette: 'palette',
	lightbulb: 'bulb',
	rocket: 'rocket',
	heart: 'heart',
	paintbrush: 'brush',
	brain: 'brain',
	globe: 'globe',
	user: 'user',
	image: 'photo',
	link: 'link',
	check: 'check',
	'rotate-ccw': 'rotate-2',
	play: 'player-play',
	pause: 'player-pause',
	home: 'home',
	'message-circle': 'message-circle',
	inbox: 'inbox',
	pencil: 'pencil',
	scaling: 'resize',
	'skip-forward': 'player-skip-forward',
	'corner-down-right': 'corner-down-right',
	'corner-down-left': 'corner-down-left',
	'panel-left': 'layout-sidebar',
	'panel-right': 'layout-sidebar-right',
	'chevrons-up-down': 'selector',
	'more-horizontal': 'dots',
	'more-vertical': 'dots-vertical',
	calendar: 'calendar',
	folder: 'folder',
	'sliders-horizontal': 'adjustments-horizontal',
	info: 'info-circle',
}

const ph: Record<FfSlot, string> = {
	'chevron-right': 'caret-right',
	'chevron-down': 'caret-down',
	pipette: 'eyedropper',
	x: 'x',
	copy: 'copy',
	menu: 'list',
	dot: 'dot-outline',
	monitor: 'monitor',
	sun: 'sun',
	moon: 'moon',
	'rectangle-horizontal': 'rectangle',
	circle: 'circle',
	'square-library': 'books',
	clock: 'clock',
	star: 'star',
	settings: 'gear',
	plus: 'plus',
	'arrow-left': 'arrow-left',
	'arrow-right': 'arrow-right',
	'arrow-up': 'arrow-up',
	'arrow-down': 'arrow-down',
	search: 'magnifying-glass',
	loader: 'spinner',
	users: 'users',
	lock: 'lock',
	mail: 'envelope',
	bell: 'bell',
	shield: 'shield',
	palette: 'palette',
	lightbulb: 'lightbulb',
	rocket: 'rocket',
	heart: 'heart',
	paintbrush: 'paint-brush',
	brain: 'brain',
	globe: 'globe',
	user: 'user',
	image: 'image',
	link: 'link',
	check: 'check',
	'rotate-ccw': 'arrow-counter-clockwise',
	play: 'play',
	pause: 'pause',
	home: 'house',
	'message-circle': 'chat-circle',
	inbox: 'tray',
	pencil: 'pencil',
	scaling: 'resize',
	'skip-forward': 'skip-forward',
	'corner-down-right': 'arrow-elbow-down-right',
	'corner-down-left': 'arrow-elbow-down-left',
	'panel-left': 'sidebar-simple',
	'panel-right': 'lucide/panel-right',
	'chevrons-up-down': 'caret-up-down',
	'more-horizontal': 'dots-three',
	'more-vertical': 'dots-three-vertical',
	calendar: 'calendar-blank',
	folder: 'folder-simple',
	'sliders-horizontal': 'sliders-horizontal',
	info: 'info',
}

const hugeicons: Record<FfSlot, string> = {
	'chevron-right': 'arrow-right-01',
	'chevron-down': 'arrow-down-01',
	pipette: 'dropper',
	x: 'cancel-01',
	copy: 'copy-01',
	menu: 'menu-01',
	dot: 'circle',
	monitor: 'computer',
	sun: 'sun-01',
	moon: 'moon-01',
	'rectangle-horizontal': 'dashboard-circle',
	circle: 'circle',
	'square-library': 'library',
	clock: 'clock-01',
	star: 'star',
	settings: 'settings-01',
	plus: 'plus-sign',
	'arrow-left': 'arrow-left-01',
	'arrow-right': 'arrow-right-01',
	'arrow-up': 'arrow-up-01',
	'arrow-down': 'arrow-down-01',
	search: 'search-01',
	loader: 'loading-01',
	users: 'user-group',
	lock: 'lock',
	mail: 'mail-01',
	bell: 'notification-01',
	shield: 'shield-01',
	palette: 'paint-brush-01',
	lightbulb: 'bulb',
	rocket: 'rocket-01',
	heart: 'favourite',
	paintbrush: 'paint-brush-02',
	brain: 'brain',
	globe: 'globe',
	user: 'user',
	image: 'image-01',
	link: 'link-01',
	check: 'tick-02',
	'rotate-ccw': 'arrow-reload-horizontal',
	play: 'lucide/play',
	pause: 'lucide/pause',
	home: 'home-01',
	'message-circle': 'bubble-chat',
	inbox: 'inbox',
	pencil: 'pencil-edit-01',
	scaling: 'resize-01',
	'skip-forward': 'next',
	'corner-down-right': 'arrow-move-down-right',
	'corner-down-left': 'arrow-move-down-left',
	'panel-left': 'sidebar-left-01',
	'panel-right': 'sidebar-right-01',
	'chevrons-up-down': 'unfold-more',
	'more-horizontal': 'more-horizontal',
	'more-vertical': 'more-vertical',
	calendar: 'calendar-01',
	folder: 'folder-01',
	'sliders-horizontal': 'sliders-horizontal',
	info: 'information-circle',
}

const untitledUi: Record<FfSlot, string> = {
	'chevron-right': 'chevron-right',
	'chevron-down': 'chevron-down',
	pipette: 'dropper',
	x: 'x-close',
	copy: 'copy-01',
	menu: 'menu-01',
	dot: 'circle',
	monitor: 'monitor-01',
	sun: 'sun',
	moon: 'moon-01',
	'rectangle-horizontal': 'square',
	circle: 'circle',
	'square-library': 'book-closed',
	clock: 'clock',
	star: 'star-01',
	settings: 'settings-01',
	plus: 'plus',
	'arrow-left': 'arrow-left',
	'arrow-right': 'arrow-right',
	'arrow-up': 'arrow-up',
	'arrow-down': 'arrow-down',
	search: 'search-md',
	loader: 'loading-01',
	users: 'users-01',
	lock: 'lock-01',
	mail: 'mail-01',
	bell: 'bell-01',
	shield: 'shield-01',
	palette: 'palette',
	lightbulb: 'lightbulb-01',
	rocket: 'rocket-01',
	heart: 'heart',
	paintbrush: 'brush-01',
	brain: 'cpu-chip-01',
	globe: 'globe-01',
	user: 'user-01',
	image: 'image-01',
	link: 'link-01',
	check: 'check',
	'rotate-ccw': 'refresh-ccw-01',
	play: 'lucide/play',
	pause: 'lucide/pause',
	home: 'home-01',
	'message-circle': 'message-circle-01',
	inbox: 'inbox-01',
	pencil: 'pencil-01',
	scaling: 'scale-01',
	'skip-forward': 'skip-forward',
	'corner-down-right': 'corner-down-right',
	'corner-down-left': 'corner-down-left',
	'panel-left': 'layout-left',
	'panel-right': 'layout-right',
	'chevrons-up-down': 'chevron-selector-vertical',
	'more-horizontal': 'dots-horizontal',
	'more-vertical': 'dots-vertical',
	calendar: 'calendar',
	folder: 'folder',
	'sliders-horizontal': 'sliders-01',
	info: 'info-circle',
}

const tables: Record<string, Partial<Record<FfSlot, string>>> = {
	lucide,
	tabler,
	ph,
	hugeicons,
	'untitled-ui': untitledUi,
}

export const FF_SETS = Object.keys(tables)

/** 槽位 → `set/name`;库内名省略时默认与槽位同名 */
export function ffRef(set: string, slot: FfSlot): string {
	const table = tables[set]
	if (!table) throw new Error(`preset "ff" has no table for set "${set}"`)
	const name = table[slot] ?? slot
	return name.includes('/') ? name : `${set}/${name}`
}
