import type { Renderer } from './types.ts'

import { formatRef } from '../ref.ts'
import { toJsxBody } from './jsx.ts'
import { licenseTag } from './types.ts'

import atlasCss from './atlas.css' with { type: 'text' }

const HEADER = `// Auto-generated by sigil — do not edit. Run \`sigil etch\` to regenerate.

import type { Octane } from 'octane/jsx-runtime'

export type IconProps = Octane.JSX.IntrinsicElements['svg'] & {
\tsize?: number | string
}
`

function renderAtlas(
	icons: Parameters<Renderer['render']>[0],
	importPath: string,
): string {
	const imports = icons.map((icon) => icon.componentName).join(', ')
	const rows = icons
		.map(
			(icon) =>
				`\t{ ref: ${JSON.stringify(formatRef(icon.ref))}, name: ${JSON.stringify(
					icon.ref.name,
				)}, componentName: ${JSON.stringify(icon.componentName)}, Icon: ${
					icon.componentName
				} },`,
		)
		.join('\n')

	return `// Auto-generated by sigil — do not edit. Run \`sigil etch --atlas\` to regenerate.

import { useEffect, useMemo, useRef, useState } from 'octane'

import type { OctaneNode } from 'octane'
import type { Octane } from 'octane/jsx-runtime'

import { ${imports} } from '${importPath}'
import type { IconProps } from '${importPath}'

export type IconAtlasItem = {
\tref: string
\tname: string
\tcomponentName: string
\tIcon: (props: IconProps) => OctaneNode
}

export const iconAtlasItems: IconAtlasItem[] = [
${rows}
]

export type IconAtlasProps = {
\tclassName?: string
\ttitle?: string
\tstyle?: Octane.JSX.IntrinsicElements['section']['style']
\tonSelect?: (item: IconAtlasItem) => void
}

export function IconAtlas(props: IconAtlasProps) @{
\tconst [query, setQuery] = useState('')
\tconst [copiedRef, setCopiedRef] = useState<string | null>(null)
\tconst searchInputRef = useRef<HTMLInputElement | null>(null)
\tconst normalizedQuery = query.trim().toLowerCase()
\tconst items = useMemo(
\t\t() =>
\t\t\tnormalizedQuery
\t\t\t\t? iconAtlasItems.filter((item) =>
\t\t\t\t\t\t[item.ref, item.name, item.componentName, item.name.replaceAll('-', ' ')]
\t\t\t\t\t\t\t.join(' ')
\t\t\t\t\t\t\t.toLowerCase()
\t\t\t\t\t\t\t.includes(normalizedQuery),
\t\t\t\t\t)
\t\t\t\t: iconAtlasItems,
\t\t[normalizedQuery],
\t)
\tconst title = props.title ?? 'Icon Atlas'

\tuseEffect(() => {
\t\tconst onKeyDown = (event: KeyboardEvent) => {
\t\t\tconst target = event.target as HTMLElement | null
\t\t\tconst isTyping =
\t\t\t\ttarget?.tagName === 'INPUT' ||
\t\t\t\ttarget?.tagName === 'TEXTAREA' ||
\t\t\t\ttarget?.isContentEditable
\t\t\tif (isTyping) return
\t\t\tif (
\t\t\t\tevent.key === '/' ||
\t\t\t((event.metaKey || event.ctrlKey) && event.key.toLowerCase() === 'k')
\t\t\t) {
\t\t\t\tevent.preventDefault()
\t\t\t\tsearchInputRef.current?.focus()
\t\t\t}
\t\t}
\t\twindow.addEventListener('keydown', onKeyDown)
\t\treturn () => window.removeEventListener('keydown', onKeyDown)
\t}, [])

\tconst selectItem = async (item: IconAtlasItem) => {
\t\tprops.onSelect?.(item)
\t\tif (typeof navigator !== 'undefined' && navigator.clipboard) {
\t\t\tawait navigator.clipboard.writeText(item.ref)
\t\t\tsetCopiedRef(item.ref)
\t\t\twindow.setTimeout(() => setCopiedRef(null), 1200)
\t\t}
\t}

\t<section
\t\tclassName={['sigil-atlas', props.className].filter(Boolean).join(' ')}
\t\tstyle={props.style}
\t>
\t\t<style>
${atlasCss}
\t\t</style>
\t\t<header className="sigil-atlas__bar">
\t\t\t<h1 className="sigil-atlas__title">{title}</h1>
\t\t\t<div className="sigil-atlas__count">
\t\t\t\t{items.length} of {iconAtlasItems.length} icons
\t\t\t</div>
\t\t\t<div className="sigil-atlas__search-wrap">
\t\t\t\t<span className="sigil-atlas__search-icon" aria-hidden="true">Search</span>
\t\t\t\t<input
\t\t\t\t\tref={searchInputRef}
\t\t\t\t\tclassName="sigil-atlas__search"
\t\t\t\t\taria-label="Search icons"
\t\t\t\t\tplaceholder={\`Search \${iconAtlasItems.length} icons...\`}
\t\t\t\t\tvalue={query}
\t\t\t\t\tonInput={(event) => setQuery(event.currentTarget.value)}
\t\t\t\t/>
\t\t\t\t@if (query) {
\t\t\t\t\t<button className="sigil-atlas__clear" type="button" onClick={() => setQuery('')}>
\t\t\t\t\t\tClear
\t\t\t\t\t</button>
\t\t\t\t}
\t\t\t\t<kbd className="sigil-atlas__shortcut">/</kbd>
\t\t\t</div>
\t\t</header>
\t\t@if (items.length === 0) {
\t\t\t<div className="sigil-atlas__empty">
\t\t\t\t<div>No icons match your search.</div>
\t\t\t</div>
\t\t} @else {
\t\t\t<div className="sigil-atlas__grid">
\t\t\t\t@for (const item of items; key item.ref) {
\t\t\t\t\t<button
\t\t\t\t\t\ttype="button"
\t\t\t\t\t\ttitle={item.ref}
\t\t\t\t\t\taria-label={\`Copy \${item.ref}\`}
\t\t\t\t\t\tclassName="sigil-atlas__tile"
\t\t\t\t\t\tdata-copied={copiedRef === item.ref}
\t\t\t\t\t\tonClick={() => void selectItem(item)}
\t\t\t\t\t>
\t\t\t\t\t\t@if (copiedRef === item.ref) {
\t\t\t\t\t\t\t<span className="sigil-atlas__copied">Copied</span>
\t\t\t\t\t\t}
\t\t\t\t\t\t<{item.Icon} className="sigil-atlas__icon" size={28} aria-hidden="true" />
\t\t\t\t\t\t<span className="sigil-atlas__label">{item.name}</span>
\t\t\t\t\t</button>
\t\t\t\t}
\t\t\t</div>
\t\t}
\t</section>
}
`
}

export const octaneRenderer: Renderer = {
	id: 'octane',
	defaultFile: 'icons.tsrx',
	render(icons, options) {
		const parts = icons.map(
			(icon) =>
				`// ${formatRef(icon.ref)}${licenseTag(icon)}\n` +
				`export function ${icon.componentName}(props: IconProps) @{\n` +
				`\tconst { size = '1em', ...svgProps } = props\n` +
				`\t<svg xmlns="http://www.w3.org/2000/svg" width={size} height={size} viewBox="${icon.viewBox}" {...svgProps}>${toJsxBody(icon.body)}</svg>\n` +
				`}`,
		)
		const files = [
			{ path: 'icons.tsrx', content: [HEADER, ...parts].join('\n') + '\n' },
		]
		if (options?.atlas) {
			files.push({
				path: options.atlasFileName ?? 'icons.atlas.tsrx',
				content:
					renderAtlas(icons, options.atlasImportPath ?? './icons.tsrx') + '\n',
			})
		}
		return files
	},
}
