import type { Renderer } from './types.ts'

import { formatRef } from '../ref.ts'
import { licenseTag } from './types.ts'

import atlasCss from './atlas.css' with { type: 'text' }

/**
 * 原生 SVG 属性 → React JSX。通用规则而非枚举表: kebab → camel(data-/aria- 前缀除外),class →
 * className,xlink:href → xlinkHref。 Iconify body 统一双引号属性,值内不会出现
 * `="`,正则按属性位置匹配是安全的。
 */
export function toReactBody(body: string): string {
	return body
		.replace(/(\s)class="/g, '$1className="')
		.replace(/(\s)xlink:href="/g, '$1xlinkHref="')
		.replace(/(\s)([a-z][a-z0-9]*(?:-[a-z0-9]+)+)="/g, (m, ws, name: string) =>
			name.startsWith('data-') || name.startsWith('aria-')
				? m
				: ws +
					name.replace(/-([a-z0-9])/g, (_, c: string) => c.toUpperCase()) +
					'="',
		)
}

const HEADER = `// Auto-generated by sigil — do not edit. Run \`sigil etch\` to regenerate.

import type { SVGProps } from 'react'

export type IconProps = SVGProps<SVGSVGElement> & { size?: number | string }

// 外壳保持中性:fill/stroke 语义在各图标 body 内,写死会破坏描边型图标。
// props 展开在默认值之后,size/className 等永远可被调用方覆盖。
const Icon = ({
	size = '1em',
	children,
	...props
}: IconProps & { viewBox: string }) => (
	<svg xmlns="http://www.w3.org/2000/svg" width={size} height={size} {...props}>
		{children}
	</svg>
)
`

function renderAtlas(
	icons: Parameters<Renderer['render']>[0],
	importPath: string,
): string {
	const imports = icons.map((icon) => icon.componentName).join(', ')
	const rows = icons
		.map(
			(icon) =>
				`\t{ ref: ${JSON.stringify(formatRef(icon.ref))}, name: ${JSON.stringify(
					icon.ref.name,
				)}, componentName: ${JSON.stringify(icon.componentName)}, Icon: ${
					icon.componentName
				} },`,
		)
		.join('\n')

	return `// Auto-generated by sigil — do not edit. Run \`sigil etch --atlas\` to regenerate.

import { useEffect, useMemo, useRef, useState } from 'react'

import type { ComponentType, CSSProperties } from 'react'

import { ${imports} } from '${importPath}'
import type { IconProps } from '${importPath}'

export type IconAtlasItem = {
\tref: string
\tname: string
\tcomponentName: string
\tIcon: ComponentType<IconProps>
}

export const iconAtlasItems: IconAtlasItem[] = [
${rows}
]

export type IconAtlasProps = {
\tclassName?: string
\ttitle?: string
\tstyle?: CSSProperties
\tonSelect?: (item: IconAtlasItem) => void
}

const iconAtlasCss = ${JSON.stringify(atlasCss)}

export const IconAtlas = (props: IconAtlasProps) => {
\tconst [query, setQuery] = useState('')
\tconst [copiedRef, setCopiedRef] = useState<string | null>(null)
\tconst searchInputRef = useRef<HTMLInputElement>(null)
\tconst normalizedQuery = query.trim().toLowerCase()
\tconst items = useMemo(
\t\t() =>
\t\t\tnormalizedQuery
\t\t\t\t? iconAtlasItems.filter((item) =>
\t\t\t\t\t\t[item.ref, item.name, item.componentName, item.name.replaceAll('-', ' ')]
\t\t\t\t\t\t\t.join(' ')
\t\t\t\t\t\t\t.toLowerCase()
\t\t\t\t\t\t\t.includes(normalizedQuery),
\t\t\t\t\t)
\t\t\t\t: iconAtlasItems,
\t\t[normalizedQuery],
\t)
\tconst title = props.title ?? 'Icon Atlas'

\tuseEffect(() => {
\t\tconst onKeyDown = (event: KeyboardEvent) => {
\t\t\tconst target = event.target as HTMLElement | null
\t\t\tconst isTyping =
\t\t\t\ttarget?.tagName === 'INPUT' ||
\t\t\t\ttarget?.tagName === 'TEXTAREA' ||
\t\t\t\ttarget?.isContentEditable
\t\t\tif (isTyping) return
\t\t\tif (
\t\t\t\tevent.key === '/' ||
\t\t\t\t((event.metaKey || event.ctrlKey) && event.key.toLowerCase() === 'k')
\t\t\t) {
\t\t\t\tevent.preventDefault()
\t\t\t\tsearchInputRef.current?.focus()
\t\t\t}
\t\t}
\t\twindow.addEventListener('keydown', onKeyDown)
\t\treturn () => window.removeEventListener('keydown', onKeyDown)
\t}, [])

\tconst selectItem = async (item: IconAtlasItem) => {
\t\tprops.onSelect?.(item)
\t\tif (typeof navigator !== 'undefined' && navigator.clipboard) {
\t\t\tawait navigator.clipboard.writeText(item.ref)
\t\t\tsetCopiedRef(item.ref)
\t\t\twindow.setTimeout(() => setCopiedRef(null), 1200)
\t\t}
\t}

\treturn (
\t\t<section className={['sigil-atlas', props.className].filter(Boolean).join(' ')} style={props.style}>
\t\t\t<style>{iconAtlasCss}</style>
\t\t\t<header className="sigil-atlas__bar">
\t\t\t\t<h1 className="sigil-atlas__title">{title}</h1>
\t\t\t\t<div className="sigil-atlas__count">
\t\t\t\t\t{items.length} of {iconAtlasItems.length} icons
\t\t\t\t</div>
\t\t\t\t<div className="sigil-atlas__search-wrap">
\t\t\t\t\t<span className="sigil-atlas__search-icon" aria-hidden="true">Search</span>
\t\t\t\t\t<input
\t\t\t\t\t\tref={searchInputRef}
\t\t\t\t\t\tclassName="sigil-atlas__search"
\t\t\t\t\t\taria-label="Search icons"
\t\t\t\t\t\tplaceholder={\`Search \${iconAtlasItems.length} icons...\`}
\t\t\t\t\t\tvalue={query}
\t\t\t\t\t\tonChange={(event) => setQuery(event.currentTarget.value)}
\t\t\t\t\t/>
\t\t\t\t\t{query ? (
\t\t\t\t\t\t<button className="sigil-atlas__clear" type="button" onClick={() => setQuery('')}>
\t\t\t\t\t\t\tClear
\t\t\t\t\t\t</button>
\t\t\t\t\t) : null}
\t\t\t\t\t<kbd className="sigil-atlas__shortcut">/</kbd>
\t\t\t\t</div>
\t\t\t</header>
\t\t\t{items.length === 0 ? (
\t\t\t\t<div className="sigil-atlas__empty">
\t\t\t\t\t<div>No icons match your search.</div>
\t\t\t\t</div>
\t\t\t) : (
\t\t\t\t<div className="sigil-atlas__grid">
\t\t\t\t\t{items.map((item) => {
\t\t\t\t\t\tconst ItemIcon = item.Icon
\t\t\t\t\t\tconst copied = copiedRef === item.ref
\t\t\t\t\t\treturn (
\t\t\t\t\t\t\t<button
\t\t\t\t\t\t\t\tkey={item.ref}
\t\t\t\t\t\t\t\ttype="button"
\t\t\t\t\t\t\t\ttitle={item.ref}
\t\t\t\t\t\t\t\taria-label={\`Copy \${item.ref}\`}
\t\t\t\t\t\t\t\tclassName="sigil-atlas__tile"
\t\t\t\t\t\t\t\tdata-copied={copied}
\t\t\t\t\t\t\t\tonClick={() => void selectItem(item)}
\t\t\t\t\t\t\t>
\t\t\t\t\t\t\t\t{copied ? <span className="sigil-atlas__copied">Copied</span> : null}
\t\t\t\t\t\t\t\t<ItemIcon className="sigil-atlas__icon" size={28} aria-hidden="true" />
\t\t\t\t\t\t\t\t<span className="sigil-atlas__label">{item.name}</span>
\t\t\t\t\t\t\t</button>
\t\t\t\t\t\t)
\t\t\t\t\t})}
\t\t\t\t</div>
\t\t\t)}
\t\t</section>
\t)
}
`
}

export const reactRenderer: Renderer = {
	id: 'react',
	defaultFile: 'icons.tsx',
	render(icons, options) {
		const parts = icons.map(
			(icon) =>
				`// ${formatRef(icon.ref)}${licenseTag(icon)}\n` +
				`export const ${icon.componentName} = (props: IconProps) => (\n` +
				`\t<Icon viewBox="${icon.viewBox}" {...props}>${toReactBody(icon.body)}</Icon>\n` +
				`)`,
		)
		const files = [
			{ path: 'icons.tsx', content: [HEADER, ...parts].join('\n') + '\n' },
		]
		if (options?.atlas) {
			files.push({
				path: options.atlasFileName ?? 'icons.atlas.tsx',
				content:
					renderAtlas(icons, options.atlasImportPath ?? './icons') + '\n',
			})
		}
		return files
	},
}
