import type { Renderer } from './types.ts'

import { formatRef } from '../ref.ts'
import { licenseTag } from './types.ts'

/**
 * 原生 SVG 属性 → React JSX。通用规则而非枚举表: kebab → camel(data-/aria- 前缀除外),class →
 * className,xlink:href → xlinkHref。 Iconify body 统一双引号属性,值内不会出现
 * `="`,正则按属性位置匹配是安全的。
 */
export function toReactBody(body: string): string {
	return body
		.replace(/(\s)class="/g, '$1className="')
		.replace(/(\s)xlink:href="/g, '$1xlinkHref="')
		.replace(/(\s)([a-z][a-z0-9]*(?:-[a-z0-9]+)+)="/g, (m, ws, name: string) =>
			name.startsWith('data-') || name.startsWith('aria-')
				? m
				: ws +
					name.replace(/-([a-z0-9])/g, (_, c: string) => c.toUpperCase()) +
					'="',
		)
}

const HEADER = `// Auto-generated by sigil — do not edit. Run \`sigil etch\` to regenerate.

import type { SVGProps } from 'react'

export type IconProps = SVGProps<SVGSVGElement> & { size?: number | string }

// 外壳保持中性:fill/stroke 语义在各图标 body 内,写死会破坏描边型图标。
// props 展开在默认值之后,size/className 等永远可被调用方覆盖。
const Icon = ({
	size = '1em',
	children,
	...props
}: IconProps & { viewBox: string }) => (
	<svg xmlns="http://www.w3.org/2000/svg" width={size} height={size} {...props}>
		{children}
	</svg>
)
`

export const reactRenderer: Renderer = {
	id: 'react',
	defaultFile: 'icons.tsx',
	render(icons) {
		const parts = icons.map(
			(icon) =>
				`// ${formatRef(icon.ref)}${licenseTag(icon)}\n` +
				`export const ${icon.componentName} = (props: IconProps) => (\n` +
				`\t<Icon viewBox="${icon.viewBox}" {...props}>${toReactBody(icon.body)}</Icon>\n` +
				`)`,
		)
		return [
			{ path: 'icons.tsx', content: [HEADER, ...parts].join('\n') + '\n' },
		]
	},
}
