import type { Renderer } from './types.ts'

import { formatRef } from '../ref.ts'
import { licenseTag } from './types.ts'

/**
 * 原生 SVG 属性 → React JSX。通用规则而非枚举表: kebab → camel(data-/aria- 前缀除外),class →
 * className,xlink:href → xlinkHref。 Iconify body 统一双引号属性,值内不会出现
 * `="`,正则按属性位置匹配是安全的。
 */
export function toReactBody(body: string): string {
	return body
		.replace(/(\s)class="/g, '$1className="')
		.replace(/(\s)xlink:href="/g, '$1xlinkHref="')
		.replace(/(\s)([a-z][a-z0-9]*(?:-[a-z0-9]+)+)="/g, (m, ws, name: string) =>
			name.startsWith('data-') || name.startsWith('aria-')
				? m
				: ws +
					name.replace(/-([a-z0-9])/g, (_, c: string) => c.toUpperCase()) +
					'="',
		)
}

function header(includeAtlas: boolean): string {
	const hooksImport = includeAtlas
		? "\nimport { useMemo, useState } from 'react'\n"
		: '\n'
	const typeImport = includeAtlas
		? "import type { ComponentType, CSSProperties, SVGProps } from 'react'"
		: "import type { SVGProps } from 'react'"

	return `// Auto-generated by sigil — do not edit. Run \`sigil etch\` to regenerate.
${hooksImport}
${typeImport}

export type IconProps = SVGProps<SVGSVGElement> & { size?: number | string }

// 外壳保持中性:fill/stroke 语义在各图标 body 内,写死会破坏描边型图标。
// props 展开在默认值之后,size/className 等永远可被调用方覆盖。
const Icon = ({
	size = '1em',
	children,
	...props
}: IconProps & { viewBox: string }) => (
	<svg xmlns="http://www.w3.org/2000/svg" width={size} height={size} {...props}>
		{children}
	</svg>
)
`
}

function renderAtlas(icons: Parameters<Renderer['render']>[0]): string {
	const rows = icons
		.map(
			(icon) =>
				`\t{ ref: ${JSON.stringify(formatRef(icon.ref))}, name: ${JSON.stringify(
					icon.ref.name,
				)}, componentName: ${JSON.stringify(icon.componentName)}, Icon: ${
					icon.componentName
				} },`,
		)
		.join('\n')

	return `
export type IconAtlasItem = {
\tref: string
\tname: string
\tcomponentName: string
\tIcon: ComponentType<IconProps>
}

export const iconAtlasItems: IconAtlasItem[] = [
${rows}
]

export type IconAtlasProps = {
\tclassName?: string
\tstyle?: CSSProperties
\tonSelect?: (item: IconAtlasItem) => void
}

const iconAtlasStyles = {
\troot: {
\t\tdisplay: 'grid',
\t\tgap: 16,
\t\tcolor: 'currentColor',
\t},
\tsearch: {
\t\twidth: '100%',
\t\tboxSizing: 'border-box',
\t\tborder: '1px solid color-mix(in srgb, currentColor 18%, transparent)',
\t\tborderRadius: 8,
\t\tpadding: '12px 14px',
\t\tfont: 'inherit',
\t\tcolor: 'inherit',
\t\tbackground: 'transparent',
\t},
\tmeta: {
\t\tfontSize: 12,
\t\topacity: 0.68,
\t},
\tgrid: {
\t\tdisplay: 'grid',
\t\tgridTemplateColumns: 'repeat(auto-fill, minmax(88px, 1fr))',
\t\tgap: 10,
\t},
\ttile: {
\t\tdisplay: 'grid',
\t\tplaceItems: 'center',
\t\tgap: 8,
\t\tminHeight: 82,
\t\tborder: 0,
\t\tborderRadius: 8,
\t\tpadding: 10,
\t\tcolor: 'inherit',
\t\tbackground: 'color-mix(in srgb, currentColor 6%, transparent)',
\t\tcursor: 'pointer',
\t},
\tlabel: {
\t\tmaxWidth: '100%',
\t\toverflow: 'hidden',
\t\ttextOverflow: 'ellipsis',
\t\twhiteSpace: 'nowrap',
\t\tfontSize: 11,
\t\topacity: 0.72,
\t},
} satisfies Record<string, CSSProperties>

export const IconAtlas = (props: IconAtlasProps) => {
\tconst [query, setQuery] = useState('')
\tconst normalizedQuery = query.trim().toLowerCase()
\tconst items = useMemo(
\t\t() =>
\t\t\tnormalizedQuery
\t\t\t\t? iconAtlasItems.filter((item) =>
\t\t\t\t\t\t[item.ref, item.name, item.componentName]
\t\t\t\t\t\t\t.join(' ')
\t\t\t\t\t\t\t.toLowerCase()
\t\t\t\t\t\t\t.includes(normalizedQuery),
\t\t\t\t\t)
\t\t\t\t: iconAtlasItems,
\t\t[normalizedQuery],
\t)

\treturn (
\t\t<section className={props.className} style={{ ...iconAtlasStyles.root, ...props.style }}>
\t\t\t<input
\t\t\t\taria-label="Search icons"
\t\t\t\tplaceholder={\`Search \${iconAtlasItems.length} icons...\`}
\t\t\t\tstyle={iconAtlasStyles.search}
\t\t\t\tvalue={query}
\t\t\t\tonChange={(event) => setQuery(event.currentTarget.value)}
\t\t\t/>
\t\t\t<div style={iconAtlasStyles.meta}>{items.length} icons</div>
\t\t\t<div style={iconAtlasStyles.grid}>
\t\t\t\t{items.map((item) => {
\t\t\t\t\tconst ItemIcon = item.Icon
\t\t\t\t\treturn (
\t\t\t\t\t\t<button
\t\t\t\t\t\t\tkey={item.ref}
\t\t\t\t\t\t\ttype="button"
\t\t\t\t\t\t\ttitle={item.ref}
\t\t\t\t\t\t\taria-label={item.ref}
\t\t\t\t\t\t\tstyle={iconAtlasStyles.tile}
\t\t\t\t\t\t\tonClick={() => props.onSelect?.(item)}
\t\t\t\t\t\t>
\t\t\t\t\t\t\t<ItemIcon size={28} aria-hidden="true" />
\t\t\t\t\t\t\t<span style={iconAtlasStyles.label}>{item.name}</span>
\t\t\t\t\t\t</button>
\t\t\t\t\t)
\t\t\t\t})}
\t\t\t</div>
\t\t</section>
\t)
}
`
}

export const reactRenderer: Renderer = {
	id: 'react',
	defaultFile: 'icons.tsx',
	render(icons, options) {
		const parts = icons.map(
			(icon) =>
				`// ${formatRef(icon.ref)}${licenseTag(icon)}\n` +
				`export const ${icon.componentName} = (props: IconProps) => (\n` +
				`\t<Icon viewBox="${icon.viewBox}" {...props}>${toReactBody(icon.body)}</Icon>\n` +
				`)`,
		)
		if (options?.atlas) parts.push(renderAtlas(icons))
		return [
			{
				path: 'icons.tsx',
				content: [header(options?.atlas ?? false), ...parts].join('\n') + '\n',
			},
		]
	},
}
