import type { Renderer } from './types.ts'

import { formatRef } from '../ref.ts'
import { licenseTag } from './types.ts'

// Solid JSX 接受原生 SVG 属性名(kebab-case / class),body 原样内联
function header(includeAtlas: boolean): string {
	const solidImport = includeAtlas
		? "import { For, createMemo, createSignal, splitProps } from 'solid-js'"
		: "import { splitProps } from 'solid-js'"
	const typeImport = includeAtlas
		? "import type { Component, JSX } from 'solid-js'"
		: "import type { JSX } from 'solid-js'"

	return `// Auto-generated by sigil — do not edit. Run \`sigil etch\` to regenerate.

${solidImport}

${typeImport}

export type IconProps = JSX.SvgSVGAttributes<SVGSVGElement> & {
	size?: number | string
}

// 外壳保持中性:fill/stroke 语义在各图标 body 内,写死会破坏描边型图标
const Icon = (props: IconProps & { viewBox: string }) => {
	const [local, rest] = splitProps(props, ['size'])
	return (
		<svg
			xmlns="http://www.w3.org/2000/svg"
			width={local.size ?? '1em'}
			height={local.size ?? '1em'}
			{...rest}
		/>
	)
}
`
}

function renderAtlas(icons: Parameters<Renderer['render']>[0]): string {
	const rows = icons
		.map(
			(icon) =>
				`\t{ ref: ${JSON.stringify(formatRef(icon.ref))}, name: ${JSON.stringify(
					icon.ref.name,
				)}, componentName: ${JSON.stringify(icon.componentName)}, Icon: ${
					icon.componentName
				} },`,
		)
		.join('\n')

	return `
export type IconAtlasItem = {
\tref: string
\tname: string
\tcomponentName: string
\tIcon: Component<IconProps>
}

export const iconAtlasItems: IconAtlasItem[] = [
${rows}
]

export type IconAtlasProps = {
\tclass?: string
\tstyle?: JSX.CSSProperties
\tonSelect?: (item: IconAtlasItem) => void
}

const iconAtlasStyles = {
\troot: {
\t\tdisplay: 'grid',
\t\tgap: '16px',
\t\tcolor: 'currentColor',
\t},
\tsearch: {
\t\twidth: '100%',
\t\t'box-sizing': 'border-box',
\t\tborder: '1px solid color-mix(in srgb, currentColor 18%, transparent)',
\t\t'border-radius': '8px',
\t\tpadding: '12px 14px',
\t\tfont: 'inherit',
\t\tcolor: 'inherit',
\t\tbackground: 'transparent',
\t},
\tmeta: {
\t\t'font-size': '12px',
\t\topacity: 0.68,
\t},
\tgrid: {
\t\tdisplay: 'grid',
\t\t'grid-template-columns': 'repeat(auto-fill, minmax(88px, 1fr))',
\t\tgap: '10px',
\t},
\ttile: {
\t\tdisplay: 'grid',
\t\t'place-items': 'center',
\t\tgap: '8px',
\t\t'min-height': '82px',
\t\tborder: 0,
\t\t'border-radius': '8px',
\t\tpadding: '10px',
\t\tcolor: 'inherit',
\t\tbackground: 'color-mix(in srgb, currentColor 6%, transparent)',
\t\tcursor: 'pointer',
\t},
\tlabel: {
\t\t'max-width': '100%',
\t\toverflow: 'hidden',
\t\t'text-overflow': 'ellipsis',
\t\t'white-space': 'nowrap',
\t\t'font-size': '11px',
\t\topacity: 0.72,
\t},
} satisfies Record<string, JSX.CSSProperties>

export const IconAtlas = (props: IconAtlasProps) => {
\tconst [query, setQuery] = createSignal('')
\tconst items = createMemo(() => {
\t\tconst normalizedQuery = query().trim().toLowerCase()
\t\treturn normalizedQuery
\t\t\t? iconAtlasItems.filter((item) =>
\t\t\t\t\t[item.ref, item.name, item.componentName]
\t\t\t\t\t\t.join(' ')
\t\t\t\t\t\t.toLowerCase()
\t\t\t\t\t\t.includes(normalizedQuery),
\t\t\t\t)
\t\t\t: iconAtlasItems
\t})

\treturn (
\t\t<section class={props.class} style={{ ...iconAtlasStyles.root, ...props.style }}>
\t\t\t<input
\t\t\t\taria-label="Search icons"
\t\t\t\tplaceholder={\`Search \${iconAtlasItems.length} icons...\`}
\t\t\t\tstyle={iconAtlasStyles.search}
\t\t\t\tvalue={query()}
\t\t\t\tonInput={(event) => setQuery(event.currentTarget.value)}
\t\t\t/>
\t\t\t<div style={iconAtlasStyles.meta}>{items().length} icons</div>
\t\t\t<div style={iconAtlasStyles.grid}>
\t\t\t\t<For each={items()}>
\t\t\t\t\t{(item) => {
\t\t\t\t\t\tconst ItemIcon = item.Icon
\t\t\t\t\t\treturn (
\t\t\t\t\t\t\t<button
\t\t\t\t\t\t\t\ttype="button"
\t\t\t\t\t\t\t\ttitle={item.ref}
\t\t\t\t\t\t\t\taria-label={item.ref}
\t\t\t\t\t\t\t\tstyle={iconAtlasStyles.tile}
\t\t\t\t\t\t\t\tonClick={() => props.onSelect?.(item)}
\t\t\t\t\t\t\t>
\t\t\t\t\t\t\t\t<ItemIcon size={28} aria-hidden="true" />
\t\t\t\t\t\t\t\t<span style={iconAtlasStyles.label}>{item.name}</span>
\t\t\t\t\t\t\t</button>
\t\t\t\t\t\t)
\t\t\t\t\t}}
\t\t\t\t</For>
\t\t\t</div>
\t\t</section>
\t)
}
`
}

export const solidRenderer: Renderer = {
	id: 'solid',
	defaultFile: 'icons.tsx',
	render(icons, options) {
		const parts = icons.map(
			(icon) =>
				`// ${formatRef(icon.ref)}${licenseTag(icon)}\n` +
				`export const ${icon.componentName} = (props: IconProps) => (\n` +
				`\t<Icon viewBox="${icon.viewBox}" {...props}>${icon.body}</Icon>\n` +
				`)`,
		)
		if (options?.atlas) parts.push(renderAtlas(icons))
		return [
			{
				path: 'icons.tsx',
				content: [header(options?.atlas ?? false), ...parts].join('\n') + '\n',
			},
		]
	},
}
