import type { Renderer } from './types.ts'

import { formatRef } from '../ref.ts'
import { licenseTag } from './types.ts'

// Solid JSX 接受原生 SVG 属性名(kebab-case / class),body 原样内联
const HEADER = `// Auto-generated by sigil — do not edit. Run \`sigil etch\` to regenerate.

import { splitProps } from 'solid-js'

import type { JSX } from 'solid-js'

export type IconProps = JSX.SvgSVGAttributes<SVGSVGElement> & {
	size?: number | string
}

// 外壳保持中性:fill/stroke 语义在各图标 body 内,写死会破坏描边型图标
const Icon = (props: IconProps & { viewBox: string }) => {
	const [local, rest] = splitProps(props, ['size'])
	return (
		<svg
			xmlns="http://www.w3.org/2000/svg"
			width={local.size ?? '1em'}
			height={local.size ?? '1em'}
			{...rest}
		/>
	)
}
`

export const solidRenderer: Renderer = {
	id: 'solid',
	defaultFile: 'icons.tsx',
	render(icons) {
		const parts = icons.map(
			(icon) =>
				`// ${formatRef(icon.ref)}${licenseTag(icon)}\n` +
				`export const ${icon.componentName} = (props: IconProps) => (\n` +
				`\t<Icon viewBox="${icon.viewBox}" {...props}>${icon.body}</Icon>\n` +
				`)`,
		)
		return [
			{ path: 'icons.tsx', content: [HEADER, ...parts].join('\n') + '\n' },
		]
	},
}
