import type { Renderer } from './types.ts'

import { formatRef } from '../ref.ts'
import { licenseTag } from './types.ts'

// TSRX (ripple-ts, https://tsrx.dev) targets Ripple. Two facts drive this output:
//   1. "TSRX keeps authored attributes as written" + Ripple uses native host
//      attributes (`class`, `stroke-width`) — so the Iconify body, which is
//      already native SVG, is inlined verbatim (no React-style renaming).
//   2. A component is a plain TS function returning JSX; `&{ }` lazy destructuring
//      keeps props reactive under Ripple's per-access model. `size ?? '1em'` lives
//      in the JSX attribute expression so it stays tracked and avoids relying on
//      defaults inside the lazy-destructure pattern.
// Output is a single `.tsrx` module. If the upstream tsrx DSL shifts, this is the
// only file to update.
const HEADER = `// Auto-generated by sigil — do not edit. Run \`sigil etch\` to regenerate.

export type IconProps = {
	size?: number | string
	// Any host SVG attribute (class, stroke-width, …) passes through to <svg>.
	[attr: string]: unknown
}
`

export const tsrxRenderer: Renderer = {
	id: 'tsrx',
	defaultFile: 'icons.tsrx',
	render(icons) {
		const parts = icons.map(
			(icon) =>
				`// ${formatRef(icon.ref)}${licenseTag(icon)}\n` +
				`export function ${icon.componentName}(&{ size, ...props }: IconProps) {\n` +
				`\treturn (\n` +
				`\t\t<svg xmlns="http://www.w3.org/2000/svg" width={size ?? '1em'} height={size ?? '1em'} viewBox="${icon.viewBox}" {...props}>${icon.body}</svg>\n` +
				`\t)\n` +
				`}`,
		)
		return [
			{ path: 'icons.tsrx', content: [HEADER, ...parts].join('\n') + '\n' },
		]
	},
}
