import type { Renderer } from './types.ts'

import { formatRef } from '../ref.ts'
import { licenseTag } from './types.ts'

import atlasCss from './atlas.css' with { type: 'text' }

// TSRX ([ripple-ts](https://www.ripple-ts.com/llms.txt), [tsrx](https://tsrx.dev/llms.txt)) targets Ripple. Three facts drive this output:
//   1. "TSRX keeps authored attributes as written" + Ripple uses native host
//      attributes (`class`, `stroke-width`) — so the Iconify body, which is
//      already native SVG, is inlined verbatim (no React-style renaming).
//   2. `IconProps` = Ripple's own `<svg>` attribute type + `size`. Ripple declares
//      `JSX` as a global ambient namespace, so `JSX.IntrinsicElements['svg']` is
//      reachable without an import (unlike Solid, whose JSX is module-scoped) and
//      gives callers typed attrs/handlers — strictly better than a `[attr]: unknown`
//      escape hatch. The base svg type has no `size`, so the intersection is clean.
//   3. The component uses the current TSRX shape — `function C(props) @{ … }`: a
//      code-block body whose trailing node IS the rendered output (no `return`).
//      `&{ size = '1em', ...props }` lazy-destructures with a per-binding default;
//      Ripple lowers that to a tracked read so it stays reactive, which is why the
//      default lives in the param, not in a `size ?? '1em'` JSX expression.
//      (Verified: ripple/tests/client/lazy-destructuring.test.tsrx.)
// Output is a single `.tsrx` module. If the upstream tsrx DSL shifts, this is the
// only file to update.
const HEADER = `// Auto-generated by sigil — do not edit. Run \`sigil etch\` to regenerate.

// JSX is a global ambient namespace in Ripple — no import needed.
export type IconProps = JSX.IntrinsicElements['svg'] & { size?: number | string }
`

function renderAtlas(
	icons: Parameters<Renderer['render']>[0],
	importPath: string,
): string {
	const imports = icons.map((icon) => icon.componentName).join(', ')
	const rows = icons
		.map(
			(icon) =>
				`\t{ ref: ${JSON.stringify(formatRef(icon.ref))}, name: ${JSON.stringify(
					icon.ref.name,
				)}, componentName: ${JSON.stringify(icon.componentName)}, Icon: ${
					icon.componentName
				} },`,
		)
		.join('\n')

	return `// Auto-generated by sigil — do not edit. Run \`sigil etch --atlas\` to regenerate.

import { track } from 'ripple'

import { ${imports} } from '${importPath}'
import type { IconProps } from '${importPath}'

export type IconAtlasItem = {
\tref: string
\tname: string
\tcomponentName: string
\tIcon: (props: IconProps) => JSX.Element
}

export const iconAtlasItems: IconAtlasItem[] = [
${rows}
]

export type IconAtlasProps = {
\tclass?: string
\ttitle?: string
\tonSelect?: (item: IconAtlasItem) => void
}

export function IconAtlas(props: IconAtlasProps = {}) @{
\tlet &[query] = track('')
\tlet &[copiedRef] = track<string | null>(null)
\tlet searchInput: HTMLInputElement | undefined
\tconst title = () => props.title ?? 'Icon Atlas'
\tconst rootClass = () => ['sigil-atlas', props.class].filter(Boolean).join(' ')
\tconst items = () => {
\t\tconst normalizedQuery = query.trim().toLowerCase()
\t\treturn normalizedQuery
\t\t\t? iconAtlasItems.filter((item) =>
\t\t\t\t\t[item.ref, item.name, item.componentName, item.name.replaceAll('-', ' ')]
\t\t\t\t\t\t.join(' ')
\t\t\t\t\t\t.toLowerCase()
\t\t\t\t\t\t.includes(normalizedQuery),
\t\t\t\t)
\t\t\t: iconAtlasItems
\t}
\tconst selectItem = async (item: IconAtlasItem) => {
\t\tprops.onSelect?.(item)
\t\tif (typeof navigator !== 'undefined' && navigator.clipboard) {
\t\t\tawait navigator.clipboard.writeText(item.ref)
\t\t\tcopiedRef = item.ref
\t\t\twindow.setTimeout(() => (copiedRef = null), 1200)
\t\t}
\t}
\tconst focusSearch = (event: KeyboardEvent) => {
\t\tconst target = event.target as HTMLElement | null
\t\tconst isTyping =
\t\t\ttarget?.tagName === 'INPUT' ||
\t\t\ttarget?.tagName === 'TEXTAREA' ||
\t\t\ttarget?.isContentEditable
\t\tif (isTyping) return
\t\tif (
\t\t\tevent.key === '/' ||
\t\t\t((event.metaKey || event.ctrlKey) && event.key.toLowerCase() === 'k')
\t\t) {
\t\t\tevent.preventDefault()
\t\t\tsearchInput?.focus()
\t\t}
\t}
\twindow.addEventListener('keydown', focusSearch)

\t<>
\t\t<section class={rootClass()}>
\t\t\t<header class="sigil-atlas__bar">
\t\t\t\t<h1 class="sigil-atlas__title">{title()}</h1>
\t\t\t\t<div class="sigil-atlas__count">
\t\t\t\t\t{items().length} of {iconAtlasItems.length} icons
\t\t\t\t</div>
\t\t\t\t<div class="sigil-atlas__search-wrap">
\t\t\t\t\t<span class="sigil-atlas__search-icon" aria-hidden="true">Search</span>
\t\t\t\t\t<input
\t\t\t\t\t\tref={searchInput}
\t\t\t\t\t\tclass="sigil-atlas__search"
\t\t\t\t\t\taria-label="Search icons"
\t\t\t\t\t\tplaceholder={\`Search \${iconAtlasItems.length} icons...\`}
\t\t\t\t\t\tvalue={query}
\t\t\t\t\t\tonInput={(event) => (query = event.currentTarget.value)}
\t\t\t\t\t/>
\t\t\t\t\t@if (query) {
\t\t\t\t\t\t<button class="sigil-atlas__clear" type="button" onClick={() => (query = '')}>
\t\t\t\t\t\t\tClear
\t\t\t\t\t\t</button>
\t\t\t\t\t}
\t\t\t\t\t<kbd class="sigil-atlas__shortcut">/</kbd>
\t\t\t\t</div>
\t\t\t</header>
\t\t\t@if (items().length === 0) {
\t\t\t\t<div class="sigil-atlas__empty">
\t\t\t\t\t<div>No icons match your search.</div>
\t\t\t\t</div>
\t\t\t} @else {
\t\t\t\t<div class="sigil-atlas__grid">
\t\t\t\t\t@for (const item of items(); key item.ref) {
\t\t\t\t\t\t<button
\t\t\t\t\t\t\ttype="button"
\t\t\t\t\t\t\ttitle={item.ref}
\t\t\t\t\t\t\taria-label={\`Copy \${item.ref}\`}
\t\t\t\t\t\t\tclass="sigil-atlas__tile"
\t\t\t\t\t\t\tdata-copied={copiedRef === item.ref}
\t\t\t\t\t\t\tonClick={() => void selectItem(item)}
\t\t\t\t\t\t>
\t\t\t\t\t\t\t@if (copiedRef === item.ref) {
\t\t\t\t\t\t\t\t<span class="sigil-atlas__copied">Copied</span>
\t\t\t\t\t\t\t}
\t\t\t\t\t\t\t<{item.Icon} class="sigil-atlas__icon" size={28} aria-hidden="true" />
\t\t\t\t\t\t\t<span class="sigil-atlas__label">{item.name}</span>
\t\t\t\t\t\t</button>
\t\t\t\t\t}
\t\t\t\t</div>
\t\t\t}
\t\t</section>
\t\t<style>
${atlasCss}
\t\t</style>
\t</>
}
`
}

export const tsrxRenderer: Renderer = {
	id: 'tsrx',
	defaultFile: 'icons.tsrx',
	render(icons, options) {
		const parts = icons.map(
			(icon) =>
				`// ${formatRef(icon.ref)}${licenseTag(icon)}\n` +
				`export function ${icon.componentName}(&{ size = '1em', ...props }: IconProps) @{\n` +
				`\t<svg xmlns="http://www.w3.org/2000/svg" width={size} height={size} viewBox="${icon.viewBox}" {...props}>${icon.body}</svg>\n` +
				`}`,
		)
		const files = [
			{ path: 'icons.tsrx', content: [HEADER, ...parts].join('\n') + '\n' },
		]
		if (options?.atlas) {
			files.push({
				path: options.atlasFileName ?? 'icons.atlas.tsrx',
				content:
					renderAtlas(icons, options.atlasImportPath ?? './icons') + '\n',
			})
		}
		return files
	},
}
