import type { Renderer } from './types.ts'

import { formatRef } from '../ref.ts'
import { licenseTag } from './types.ts'

// TSRX (ripple-ts, https://tsrx.dev) targets Ripple. Three facts drive this output:
//   1. "TSRX keeps authored attributes as written" + Ripple uses native host
//      attributes (`class`, `stroke-width`) — so the Iconify body, which is
//      already native SVG, is inlined verbatim (no React-style renaming).
//   2. `IconProps` = Ripple's own `<svg>` attribute type + `size`. Ripple declares
//      `JSX` as a global ambient namespace, so `JSX.IntrinsicElements['svg']` is
//      reachable without an import (unlike Solid, whose JSX is module-scoped) and
//      gives callers typed attrs/handlers — strictly better than a `[attr]: unknown`
//      escape hatch. The base svg type has no `size`, so the intersection is clean.
//   3. The component uses the current TSRX shape — `function C(props) @{ … }`: a
//      code-block body whose trailing node IS the rendered output (no `return`).
//      `&{ size = '1em', ...props }` lazy-destructures with a per-binding default;
//      Ripple lowers that to a tracked read so it stays reactive, which is why the
//      default lives in the param, not in a `size ?? '1em'` JSX expression.
//      (Verified: ripple/tests/client/lazy-destructuring.test.tsrx.)
// Output is a single `.tsrx` module. If the upstream tsrx DSL shifts, this is the
// only file to update.
const HEADER = `// Auto-generated by sigil — do not edit. Run \`sigil etch\` to regenerate.

// JSX is a global ambient namespace in Ripple — no import needed.
export type IconProps = JSX.IntrinsicElements['svg'] & { size?: number | string }
`

export const tsrxRenderer: Renderer = {
	id: 'tsrx',
	defaultFile: 'icons.tsrx',
	render(icons) {
		const parts = icons.map(
			(icon) =>
				`// ${formatRef(icon.ref)}${licenseTag(icon)}\n` +
				`export function ${icon.componentName}(&{ size = '1em', ...props }: IconProps) @{\n` +
				`\t<svg xmlns="http://www.w3.org/2000/svg" width={size} height={size} viewBox="${icon.viewBox}" {...props}>${icon.body}</svg>\n` +
				`}`,
		)
		return [
			{ path: 'icons.tsrx', content: [HEADER, ...parts].join('\n') + '\n' },
		]
	},
}
